apiVersion: v2 # this K8S Helm related
name: mongodb
version: 0.0.1 #This is chart version
appVersion: 1.0.0 # this is application version here nginx is app like we have catalogue,nodejs,
description: "installing 1.0.0"